### ISSUE TITLE
version_family doesn't work

### ISSUE THREAD

**Issue by bingosummer** [concourse/bosh-io-stemcell-resource#20]
```
- name: azure-centos-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-azure-hyperv-centos-7-go_agent
    version_family: 3363.latest
```

Expected: I can get `3363.25` Azure CentOS stemcell.
Actual: Still get `3421.9` Azure CentOS stemcell.
![image](https://user-images.githubusercontent.com/4787647/27629914-6bcfbd96-5c26-11e7-9d00-02b851c72692.png)

**Comment by zachgersh** [comment]
@bingosummer - interesting, thanks for reporting this. We seemed to not have any acceptance tests covering `centos` stemcells. I can't see any reason why what you did _wouldn't_ work but I am going to change the acceptance test to your case and then take it from there.

**Comment by shreddedbacon** [comment]
I am experiencing a similar issue using the bosh-warden stemcell with version_family
```
    name: bosh-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version_family: "3421.6"
```
But it always picks the latest stemcell which is currently 3421.11
If I specify a version, I expect it to use that version, not the latest.
