### ISSUE TITLE
unexpected end of JSON input error

### ISSUE THREAD

**Issue by quintessence** [concourse/bosh-io-stemcell-resource#3]
We have this:

``` yaml
resources:
- name: stemcell-aws
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
```

The error we are receiving is:

`unexpected end of JSON input`

CC: @cppforlife , @drnic
